var GAME_LEVELS = [
  ["                                x!!!x               ",
   "                                x!x!x               ",
   "                                 v v                ",
   "                                                    ",
   "  xx   o                                            ",
   "  x                                            xxx  ",
   "  x   xxx               o                        x  ",
   "  x@       o                                     x  ",
   "  x              o             o                 x  ",
   "  x       xx           xx                  o   o x  ",
   "  xxxxxxxxxxx    xx   xxxx    xxx    xxxx      o x  ",
   "            xxx   =   x  x!!!!!!!!!!!x  x        x  ",
   "             xx!!!!!!!x  x!!!!!!!!!!!x  x!!!xxxxxx  ",
   "              x!!!!!!!x  xxxxxxxxxxxxxxxxxxxxxx     ",
   "              xxxxxxxxx                             ",
   "                                                    ",
   "                                                    ",
   "                                                    "],
  ["                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",
   " xxxxxx                                                                                 ",
   " x                                                                                      ",
   " x                                                                                      ",
   " x      @                                                                               ",
   " x o                                                                                    ",
   " x     xxxx o                                                                           ",
   " xx                                                                                     ",
   "  xxx   =    xx    xxx    =     =       =      x                                        ",                               
   "    xx!!!!!!xxxx  xxxx!!!!!!!!!!!!!!!!!!!!!!!!!x                                        ",
   "     xxxxxxxx  x  xxxxxxxxxxxxxxxxxx!xxxx!!!!!!x                                        ",
   "               x    x o         x o v   x!!!!!!x                                        ",
   "               x                        x!!!!!!x                                        ",
   "               x          x             x!!!!!!x                                        ",
   "               xxxxxxxxxxxxxxxxxxxxx    x!!!!!!x                                        ",
   "                                xxxx    xxxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "                                xx     xx   v                                   x       ",
   "                                xx o                 o              o         o x       ",
   "                                xx                                          o   x       ",
   "                                xxxx    o                                     xxx       ",
   "                                xx                                          xxxxx       ",
   "                                xx    xxxx     xx   xxxxx    xx  =  xxxx   xxxxxx       ",
   "                                xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx       ",
   "                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",
   "                                                                                        "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
